// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyabjWPoDIWYgBLgFTnCcg1Fx1oqg-dA',
    appId: '1:598989124218:web:f25c015aed59077fd3c1c3',
    messagingSenderId: '598989124218',
    projectId: 'dyci-f35aa',
    authDomain: 'dyci-f35aa.firebaseapp.com',
    storageBucket: 'dyci-f35aa.firebasestorage.app',
    measurementId: 'G-Q9784XEBRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVfQGhklfXeN54-TkScQD7Dc0T_uvUEQ',
    appId: '1:598989124218:android:845fe767f903ed71d3c1c3',
    messagingSenderId: '598989124218',
    projectId: 'dyci-f35aa',
    storageBucket: 'dyci-f35aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0xkIfhmiflSCx7640q2opOU7cHnbgMQ',
    appId: '1:598989124218:ios:c47ce0f3eaacfcaad3c1c3',
    messagingSenderId: '598989124218',
    projectId: 'dyci-f35aa',
    storageBucket: 'dyci-f35aa.firebasestorage.app',
    iosBundleId: 'dev.solsynth.solian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0xkIfhmiflSCx7640q2opOU7cHnbgMQ',
    appId: '1:598989124218:ios:c47ce0f3eaacfcaad3c1c3',
    messagingSenderId: '598989124218',
    projectId: 'dyci-f35aa',
    storageBucket: 'dyci-f35aa.firebasestorage.app',
    iosBundleId: 'dev.solsynth.solian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyabjWPoDIWYgBLgFTnCcg1Fx1oqg-dA',
    appId: '1:598989124218:web:fa0ec3c3502b6145d3c1c3',
    messagingSenderId: '598989124218',
    projectId: 'dyci-f35aa',
    authDomain: 'dyci-f35aa.firebaseapp.com',
    storageBucket: 'dyci-f35aa.firebasestorage.app',
    measurementId: 'G-367CY821CB',
  );

}